import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Welcome from "@/components/Welcome/Welcome";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Welcome />

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
