name: Test

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          check-latest: true

      - name: Install 🧶
        run: yarn

      - name: Lint 🔬
        run: yarn lint

      - name: Unit tests 🧪
        run: yarn test
